version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  web: &app_base
    build: .
    env_file: .docker-env
    command: rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
  data:
    image: busybox
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./bundle:/usr/local/bundle
  spring:
    <<: *app_base
    command: bundle exec spring server
    ports: []
    tty: false
    stdin_open: false
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  mysql-data:
    driver: local
  bundle:
    driver: local
  redis-data:
    driver: local
