version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
  web:
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD
      - CHIRORU_ACCESS_ID
      - CHIRORU_SECRET_KEY
      - CHIRORU_REGION
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  mysql-data:
    driver: local