version: '3'
services:
  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
  web:
    build: .
    env_file:
      - .env
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  mysql-data:
    driver: local