version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node-browsers
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{ { checksum "Gemfile.lock" } }
            - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{ { checksum "Gemfile.lock" } }
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: install javascript package
          command: yarn add package.json
      - run:
          name: run tests
          command: bundle exec rspec
      - run:
          name: code check
          command: bundle exec rubocop --require rubocop-rails

workflows:
  version: 2
  test:
    jobs:
      - build
