version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node-browsers
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: bundle install
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - build
