version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node-browsers
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{ { checksum "Gemfile.lock" } }
            - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{ { checksum "Gemfile.lock" } }
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: install javascript package
          command: yarn add package.json
      - run:
          name: run tests
          command: bundle exec rspec
      - run:
          name: code check
          command: bundle exec rubocop --require rubocop-rails
  build_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install awd cli
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: build image
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker build -f Dockerfile.pro -t ${ECR_DOMAIN}/lovekitchen:$CIRCLE_SHA1 --build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY} --build-arg RAILS_ENV=production --build-arg CHIRORU_ACCESS_ID=${CHIRORU_ACCESS_ID} --build-arg CHIRORU_SECRET_KEY=${CHIRORU_SECRET_KEY} --build-arg CHIRORU_REGION=${CHIRORU_REGION} .
            docker build -f Dockerfile.pro -t ${ECR_DOMAIN}/lovekitchen:latest --build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY} --build-arg RAILS_ENV=production --build-arg CHIRORU_ACCESS_ID=${CHIRORU_ACCESS_ID} --build-arg CHIRORU_SECRET_KEY=${CHIRORU_SECRET_KEY} --build-arg CHIRORU_REGION=${CHIRORU_REGION} .
      - run:
          name: Push docker image
          command: |
            docker push ${ECR_DOMAIN}/lovekitchen:$CIRCLE_SHA1
            docker push ${ECR_DOMAIN}/lovekitchen:latest
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: install aws cli
          command: |
            sudo pip install awscli
      - run:
          name: download jq
          command: |
            wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
            mv jq-linux64 jq
      - run:
          name: login
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - run:
          name: deploy
          command: |
            aws ecs describe-task-definition --task-definition rails-app | jq '.taskDefinition | { containerDefinitions: .containerDefinitions }' > definition.json
            aws ecs register-task-definition --family rails-app --cli-input-json file://definition.json
            aws ecs update-service --cluster lovekitchen-cluster --service rails-service --task-definition rails-app
      - run:
          name: migration
          command: |
            aws ecs run-task --cluster lovekitchen-cluster --task-definition rails-migration
workflows:
  version: 2
  test:
    jobs:
      - build
      - build_image:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_image
          filters:
            branches:
              only: master
